routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersPermissionController;
use App\Http\Controllers\UsersRoleController;
use App\Http\Controllers\InventoryController\web\DashboardController;
use App\Http\Controllers\InventoryController\web\ProductController;
use App\Http\Controllers\InventoryController\web\EmployeeController;
use App\Http\Controllers\InventoryController\web\EmployeeLogsController;
use App\Http\Controllers\InventoryController\web\ItemBrandController;
use App\Http\Controllers\InventoryController\web\ItemCategoryController;
use App\Http\Controllers\InventoryController\web\ItemColorController;
use App\Http\Controllers\InventoryController\web\ItemSizeController;
use App\Http\Controllers\InventoryController\web\ItemTypeController;
use App\Http\Controllers\InventoryController\web\OutOfStockItemController;
use App\Http\Controllers\InventoryController\web\MostOrderedItemController;
use App\Http\Controllers\InventoryController\web\NewProductListController;

use App\Http\Controllers\OnlineExamController\web\ProfileController;
use App\Http\Controllers\OnlineExamController\web\admin\AdminExamController;
use App\Http\Controllers\OnlineExamController\web\admin\AdminExamCourseController;
use App\Http\Controllers\OnlineExamController\web\faculty\FacultyExamDashboardController;
use App\Http\Controllers\OnlineExamController\web\faculty\ExamController;
use App\Http\Controllers\OnlineExamController\web\faculty\SubjectController;
use App\Http\Controllers\OnlineExamController\web\faculty\ExamQuestionController;
use App\Http\Controllers\OnlineExamController\web\student\StudentExamController;

use App\Http\Controllers\OnlineMenuController\web\AdminDashboardController;
use App\Http\Controllers\OnlineMenuController\web\CustomerDashboardController;

use App\Http\Controllers\PayrollController\web\admin\AdminPayrollDashboardController;
use App\Http\Controllers\PayrollController\web\admin\ScheduleController;
use App\Http\Controllers\PayrollController\web\admin\CutOffController;
use App\Http\Controllers\PayrollController\web\admin\AttendanceCorrectionController;
use App\Http\Controllers\PayrollController\web\admin\HolidayController;
use App\Http\Controllers\PayrollController\web\admin\SalaryAdditionController;
use App\Http\Controllers\PayrollController\web\admin\SalaryDeductionController;
use App\Http\Controllers\PayrollController\web\admin\SalaryGradeController;
use App\Http\Controllers\PayrollController\web\admin\UserRegistrationController;

use App\Http\Controllers\PayrollController\web\employee\EmployeePayrollDashboardController;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware(['auth', 'auth:sanctum'])->group(function () {
	Route::view('/', 'home')->name('index');

	/* User's Role and Permission route */
	Route::middleware('role:Super Admin')->group(function () {
		Route::resource('userspermission', UsersPermissionController::class);
		Route::resource('usersrole', UsersRoleController::class);
	});
	/* End */
	dd(Permission::with('users')->get());
	$permissionArr = array('inventory add stock', 'inventory get stock','inventory view user', 'inventory edit user', 'inventory add new item');
	$permissionStr = implode('|', $permissionArr);
	/* Inventory Route */
	// 'permission:inventory add stock|inventory get stock|inventory view user|inventory edit user|inventory add new item'
	Route::middleware('permission:'.$permissionStr)->prefix('inventory')->group(function() {
		Route::get('/', [DashboardController::class, 'index'])->name('inventorydashboard.index');

		Route::prefix('employee')->group(function() {
			Route::middleware('permission:inventory view user|inventory edit user')->group(function () {
				Route::get('/employeelogs', [EmployeeLogsController::class, 'index'])->name('employeelogs.index');
				Route::resource('employee', EmployeeController::class);
			});
		});

		Route::prefix('product')->group(function () {
			Route::resource('size', ItemSizeController::class);
			Route::resource('color', ItemColorController::class);
			Route::resource('brand', ItemBrandController::class);
			Route::resource('type', ItemTypeController::class);
			Route::resource('category', ItemCategoryController::class);
			Route::resource('outofstock', OutOfStockItemController::class);
			Route::resource('mostordered', MostOrderedItemController::class);
			Route::resource('newproduct', NewProductListController::class);

			Route::view('/deliver', 'inventory.product.receive')->name('deliver.index');
			Route::view('/order', 'inventory.product.order')->name('order.index');
			Route::view('/ordersummary', 'inventory.product.orderSummary')->name('ordersummary.index');
		});	
		
		Route::resource('product', ProductController::class);
	});
	/* END */

	/* Online Exam route */
	Route::prefix('online-exam')->group(function() {
		Route::middleware('permission:exam admin access')->group(function () {
			Route::resource('adminexam', AdminExamController::class);
			Route::resource('courseexam', AdminExamCourseController::class);
		});

		Route::middleware('permission:exam faculty access')->group(function () {
			Route::resource('facultyexam', FacultyExamDashboardController::class);
			Route::resource('exam', ExamController::class);
			Route::resource('subjectexam', SubjectController::class);
			Route::resource('examquestion', ExamQuestionController::class);
		});

		Route::middleware('permission:exam student access')->group(function () {
			Route::resource('studentexam', StudentExamController::class);
			Route::view('/examination', 'onlineexam.student.examination');
		});

		Route::resource('profile.user', ProfileController::class);
	});
	/* END */

	/* Online Menu route */
	Route::prefix('menu-ordering')->group(function() {
		/* Customer route */
		Route::middleware('permission:menu create orders|menu view order history|menu view coupon list')->group(function () {
			Route::get('/customer', [CustomerDashboardController::class, 'index'])->name('customer.index');
		});
		/* Admin Maintenance route */
		Route::middleware('permission:menu view order list|menu view user list')->group(function(){
			Route::get('/admin', [AdminDashboardController::class, 'index'])->name('admin.index');
		});
	});
	/* END */

	/* Payroll route */
	Route::prefix('payroll')->group(function() {
		Route::view('/notregister', 'payroll.notregister')->name('notregister.index');

		/* Admin */
		Route::middleware('permission:payroll admin access')->group(function() {
			Route::resource('payrolladmin', AdminPayrollDashboardController::class);
			Route::resource('payrollschedule', ScheduleController::class);
			Route::resource('cutoff', CutOffController::class);
			Route::resource('attendancecorrection', AttendanceCorrectionController::class);
			Route::resource('holiday', HolidayController::class);
			Route::resource('salaryaddition', SalaryAdditionController::class);
			Route::resource('salarydeduction', SalaryDeductionController::class);
			Route::resource('salarygrade', SalaryGradeController::class);
			Route::resource('register', UserRegistrationController::class);
		});

		/* Employee */
		Route::middleware('permission:payroll employee access')->group(function () {
			/* Check if user is registered in payroll system */
			Route::middleware('validatepayrolluser')->group(function () {
				Route::resource('payrollemployee', EmployeePayrollDashboardController::class);
			});
		});
		Route::resource('changepassword', PayrollChangePasswordController::class);
	});
});
/* END */

app/Models/OnlineExam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OnlineExam extends Model
{
    use HasFactory; 

    protected $fillable = ['user_id', 'exam_code', 'online_subject_id', 'timer'];

    protected $casts = ['timer' => 'integer', 'online_subject_id' => 'integer'];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    public function examquestion()
    {
    	$this->hasMany(OnlineExamQuestion::class);
    }

    public function onlinesubject()
    {
    	return $this->belongsTo(OnlineSubject::class, 'online_subject_id');
    }

    public function user()
    {
    	return $this->belongsTo(User::class)->withTrashed();
    }

    public function onlineexamination()
    {
    	return $this->hasMany(OnlineExamination::class);
    }
}

resources/views/onlineexam/edit.blade.php
@extends('onlineexam.layouts.app')

@section('onlinecontent')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="navbar d-none d-md-block" 
                style="margin-bottom : -15px;">
                <ul class="navbar-nav d-flex flex-row gap-1 border-0">
                    <li class="nav-item">
                        <a href="{{ route('adminexam.index') }}" 
                            class="nav-link border border-bottom-0 rounded py-3 text-light px-5">
                            {{ __('Dashboard') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('courseexam.index') }}" 
                            class="nav-link border border-bottom-0 text-light rounded py-3 px-5">
                            {{ __('Course') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" 
                            class="nav-link border border-bottom-0 text-light rounded py-3 px-5 bg-primary">
                            @php
                                $label = '';
                                $id = 0;
                                $name = '';
                                $route = '';
                                $value = '';

                                switch ($type) {
                                    case 'subject':
                                        $label = 'Subject';
                                        $id = $subject['id'];
                                        $name = 'subject';
                                        $route = 'adminexam.update';
                                        $value = $subject['subject'];
                                        break;

                                    default:
                                        $label = 'Course';
                                        $id = $course['id'];
                                        $name = 'course';
                                        $route = 'courseexam.update';
                                        $value = $course['course'];
                                }
                            @endphp
                            {{ __('Edit ').$label }}
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card border-top-0">
                <div class="card-header border border-primary bg-primary py-4"></div>
                <div class="card-body d-grid gap-3">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-md-5">
                                <div class="card border-warning">
                                    <div class="card-header border-bottom border-warning">
                                        {{ $label }}
                                    </div>
                                    <div class="card-body">
                                        <form method="POST" 
                                            class="p-md-4" 
                                            action="{{ route($route, $id) }}">

                                            @csrf
                                            @method('PUT')

                                            <div class="form-group mb-3">
                                                <input type="text" 
                                                    name="{{ $name }}" 
                                                    value="{{ $value }}" 
                                                    class="form-control" 
                                                    autocomplete="off">
                                            </div>
                                            <div class="form-group">
                                                <div class="d-flex justify-content-end">
                                                    <input type="submit" 
                                                        value="Save" 
                                                        class="btn btn-outline-primary">
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-primary">
                    <div class="container">
                        <x-footerexam color="text-light"></x-footerexam>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
@endsection

resources/views/onlineexam/profile.blade.php
@extends('onlineexam.layouts.app')

@section('onlinecontent')
<div class="container pt-4" 
    id="app">

    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                <div class="card-header bg-primary text-light">
                    {{ __('Edit Profile') }}
                </div>
                <div class="card-body">
                    <form method="POST" 
                        action="{{ route('profile.user.update', ['profile' => $profile, 'user' => $userDetails->id]) }}">

                        @csrf
                        @method('PATCH')

                        <div class="row mb-3 justify-content-center">
                            <div class="col-md-10">
                                <label for="firstname">
                                    {{ __('First Name') }}
                                </label>
                                <input id="firstname" 
                                    type="text" 
                                    class="form-control @error('firstname') is-invalid @enderror" 
                                    name="firstname" 
                                    value="{{ $userDetails->firstname }}" 
                                    required 
                                    autofocus>

                                @error('firstname')
                                    <span class="invalid-feedback" 
                                        role="alert">

                                        <strong>
                                            {{ $message }}
                                        </strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3 justify-content-center">
                            <div class="col-md-10">
                                <label for="middlename">
                                    {{ __('Middle Name') }}
                                </label>
                                <input id="middlename" 
                                    type="text" 
                                    class="form-control" 
                                    name="middlename" 
                                    value="{{ $userDetails->middlename }}">

                            </div>
                        </div>

                        <div class="row mb-3 justify-content-center">
                            <div class="col-md-10">
                                <label for="lastname">
                                    {{ __('Last Name') }}
                                </label>
                                <input id="lastname" 
                                    type="text" 
                                    class="form-control @error('lastname') is-invalid @enderror" 
                                    name="lastname" 
                                    value="{{ $userDetails->lastname }}" 
                                    required>

                                @error('lastname')
                                    <span class="invalid-feedback" 
                                        role="alert">

                                        <strong>
                                            {{ $message }}
                                        </strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        @if($profile == 'student')
                            <div class="row mb-3 justify-content-center">
                                <div class="col-md-10">
                                    <label for="course">
                                        {{ __('Course') }}
                                    </label>
                                    <select class="form-select" 
                                        name="online_course_id" 
                                        id="course">

                                        @foreach($courses as $course)
                                            <option value="{{ $course->id }}" 
                                                @if(Auth::user()->online_course_id === $course->id) selected @endif>
                                                {{ $course->course }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endif

                        <div class="row mb-3 justify-content-center">
                            <div class="col-md-10">
                                <div class="row justify-content-center">
                                    <div class="col-md-6">
                                        <label for="DOB">
                                            {{ __('Date of Birth') }}
                                        </label>
                                        <input id="DOB" 
                                            type="date" 
                                            class="form-control @error('DOB') is-invalid @enderror" 
                                            name="DOB" 
                                            value="{{ date('Y-m-d', strtotime($userDetails->DOB)) }}" 
                                            required/>

                                        @error('DOB')
                                            <span class="invalid-feedback" 
                                                role="alert">

                                                <strong>
                                                    {{ $message }}
                                                </strong>
                                            </span>
                                        @enderror
                                    </div>
                                    <div class="col-md-6">
                                        <label class="pb-md-1">
                                            {{ __('Gender') }}
                                        </label>
                                        <div class="row">
                                            <div class="col-6 d-flex align-items-center justify-content-md-around">
                                                <label>
                                                    {{ __('Male') }}
                                                </label>
                                                &nbsp;
                                                <input id="male" 
                                                    type="radio" 
                                                    name="gender_id" 
                                                    value="1" 
                                                    @if($userDetails->gender_id === 1) checked @endif>

                                            </div>
                                            <div class="col-6 d-flex align-items-center justify-content-md-around">
                                                <label>
                                                    {{ __('Female') }}
                                                </label>
                                                &nbsp;
                                                <input 
                                                    id="female" 
                                                    type="radio" 
                                                    name="gender_id" 
                                                    value="2" 
                                                    @if($userDetails->gender_id === 2) checked @endif>

                                            </div>
                                        </div>
                                        @error('gender_id')
                                            <span class="invalid-feedback" 
                                                role="alert">

                                                <strong>
                                                    {{ $message }}
                                                </strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3 justify-content-center">
                            <div class="col-md-10">
                                <label for="email">
                                    {{ __('Email Address') }}
                                </label>
                                <input id="email" 
                                    type="email" 
                                    class="form-control @error('email') is-invalid @enderror" 
                                    name="email" 
                                    value="{{ $userDetails->email }}">

                                @error('email')
                                    <span class="invalid-feedback" 
                                        role="alert">

                                        <strong>
                                            {{ $message }}
                                        </strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        
                        <div class="row mb-3 justify-content-center pt-3">
                            <div class="col-md-10 d-flex justify-content-between align-items-center">
                                <a href="{{ url()->previous() }}" 
                                    class="btn btn-outline-info">
                                    {{ __('Cancel') }}
                                </a>
                                <button type="submit" 
                                    class="btn btn-outline-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="card-footer bg-primary">
                    <div class="container">
                        <x-footerexam color="text-light"></x-footerexam>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection