routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersPermissionController;
use App\Http\Controllers\UsersRoleController;
use App\Http\Controllers\InventoryController\web\DashboardController;
use App\Http\Controllers\InventoryController\web\ProductController;
use App\Http\Controllers\InventoryController\web\EmployeeController;
use App\Http\Controllers\InventoryController\web\EmployeeLogsController;
use App\Http\Controllers\InventoryController\web\ItemBrandController;
use App\Http\Controllers\InventoryController\web\ItemCategoryController;
use App\Http\Controllers\InventoryController\web\ItemColorController;
use App\Http\Controllers\InventoryController\web\ItemSizeController;
use App\Http\Controllers\InventoryController\web\ItemTypeController;
use App\Http\Controllers\InventoryController\web\OutOfStockItemController;
use App\Http\Controllers\InventoryController\web\MostOrderedItemController;
use App\Http\Controllers\InventoryController\web\NewProductListController;

use App\Http\Controllers\OnlineExamController\web\ProfileController;
use App\Http\Controllers\OnlineExamController\web\admin\AdminExamController;
use App\Http\Controllers\OnlineExamController\web\admin\AdminExamCourseController;
use App\Http\Controllers\OnlineExamController\web\faculty\FacultyExamDashboardController;
use App\Http\Controllers\OnlineExamController\web\faculty\ExamController;
use App\Http\Controllers\OnlineExamController\web\faculty\SubjectController;
use App\Http\Controllers\OnlineExamController\web\faculty\ExamQuestionController;
use App\Http\Controllers\OnlineExamController\web\student\StudentExamController;

use App\Http\Controllers\OnlineMenuController\web\AdminDashboardController;
use App\Http\Controllers\OnlineMenuController\web\CustomerDashboardController;

use App\Http\Controllers\PayrollController\web\admin\AdminPayrollDashboardController;
use App\Http\Controllers\PayrollController\web\admin\ScheduleController;
use App\Http\Controllers\PayrollController\web\admin\CutOffController;
use App\Http\Controllers\PayrollController\web\admin\AttendanceCorrectionController;
use App\Http\Controllers\PayrollController\web\admin\HolidayController;
use App\Http\Controllers\PayrollController\web\admin\SalaryAdditionController;
use App\Http\Controllers\PayrollController\web\admin\SalaryDeductionController;
use App\Http\Controllers\PayrollController\web\admin\SalaryGradeController;
use App\Http\Controllers\PayrollController\web\admin\UserRegistrationController;

use App\Http\Controllers\PayrollController\web\employee\EmployeePayrollDashboardController;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware(['auth', 'auth:sanctum'])->group(function () {
	Route::view('/', 'home')->name('index');

	/* User's Role and Permission route */
	Route::middleware('role:Super Admin')->group(function () {
		Route::resource('userspermission', UsersPermissionController::class);
		Route::resource('usersrole', UsersRoleController::class);
	});
	/* End */
	dd(Permission::with('users')->get());
	$permissionArr = array('inventory add stock', 'inventory get stock','inventory view user', 'inventory edit user', 'inventory add new item');
	$permissionStr = implode('|', $permissionArr);
	/* Inventory Route */
	// 'permission:inventory add stock|inventory get stock|inventory view user|inventory edit user|inventory add new item'
	Route::middleware('permission:'.$permissionStr)->prefix('inventory')->group(function() {
		Route::get('/', [DashboardController::class, 'index'])->name('inventorydashboard.index');

		Route::prefix('employee')->group(function() {
			Route::middleware('permission:inventory view user|inventory edit user')->group(function () {
				Route::get('/employeelogs', [EmployeeLogsController::class, 'index'])->name('employeelogs.index');
				Route::resource('employee', EmployeeController::class);
			});
		});

		Route::prefix('product')->group(function () {
			Route::resource('size', ItemSizeController::class);
			Route::resource('color', ItemColorController::class);
			Route::resource('brand', ItemBrandController::class);
			Route::resource('type', ItemTypeController::class);
			Route::resource('category', ItemCategoryController::class);
			Route::resource('outofstock', OutOfStockItemController::class);
			Route::resource('mostordered', MostOrderedItemController::class);
			Route::resource('newproduct', NewProductListController::class);

			Route::view('/deliver', 'inventory.product.receive')->name('deliver.index');
			Route::view('/order', 'inventory.product.order')->name('order.index');
			Route::view('/ordersummary', 'inventory.product.orderSummary')->name('ordersummary.index');
		});	
		
		Route::resource('product', ProductController::class);
	});
	/* END */

	/* Online Exam route */
	Route::prefix('online-exam')->group(function() {
		Route::middleware('permission:exam admin access')->group(function () {
			Route::resource('adminexam', AdminExamController::class);
			Route::resource('courseexam', AdminExamCourseController::class);
		});

		Route::middleware('permission:exam faculty access')->group(function () {
			Route::resource('facultyexam', FacultyExamDashboardController::class);
			Route::resource('exam', ExamController::class);
			Route::resource('subjectexam', SubjectController::class);
			Route::resource('examquestion', ExamQuestionController::class);
		});

		Route::middleware('permission:exam student access')->group(function () {
			Route::resource('studentexam', StudentExamController::class);
			Route::view('/examination', 'onlineexam.student.examination');
		});

		Route::resource('profile.user', ProfileController::class);
	});
	/* END */

	/* Online Menu route */
	Route::prefix('menu-ordering')->group(function() {
		/* Customer route */
		Route::middleware('permission:menu create orders|menu view order history|menu view coupon list')->group(function () {
			Route::get('/customer', [CustomerDashboardController::class, 'index'])->name('customer.index');
		});
		/* Admin Maintenance route */
		Route::middleware('permission:menu view order list|menu view user list')->group(function(){
			Route::get('/admin', [AdminDashboardController::class, 'index'])->name('admin.index');
		});
	});
	/* END */

	/* Payroll route */
	Route::prefix('payroll')->group(function() {
		Route::view('/notregister', 'payroll.notregister')->name('notregister.index');

		/* Admin */
		Route::middleware('permission:payroll admin access')->group(function() {
			Route::resource('payrolladmin', AdminPayrollDashboardController::class);
			Route::resource('payrollschedule', ScheduleController::class);
			Route::resource('cutoff', CutOffController::class);
			Route::resource('attendancecorrection', AttendanceCorrectionController::class);
			Route::resource('holiday', HolidayController::class);
			Route::resource('salaryaddition', SalaryAdditionController::class);
			Route::resource('salarydeduction', SalaryDeductionController::class);
			Route::resource('salarygrade', SalaryGradeController::class);
			Route::resource('register', UserRegistrationController::class);
		});

		/* Employee */
		Route::middleware('permission:payroll employee access')->group(function () {
			/* Check if user is registered in payroll system */
			Route::middleware('validatepayrolluser')->group(function () {
				Route::resource('payrollemployee', EmployeePayrollDashboardController::class);
			});
		});
		Route::resource('changepassword', PayrollChangePasswordController::class);
	});
});
/* END */

app/Models/OnlineExam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OnlineExam extends Model
{
    use HasFactory; 

    protected $fillable = ['user_id', 'exam_code', 'online_subject_id', 'timer'];

    protected $casts = ['timer' => 'integer', 'online_subject_id' => 'integer'];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    public function examquestion()
    {
    	$this->hasMany(OnlineExamQuestion::class);
    }

    public function onlinesubject()
    {
    	return $this->belongsTo(OnlineSubject::class, 'online_subject_id');
    }

    public function user()
    {
    	return $this->belongsTo(User::class)->withTrashed();
    }

    public function onlineexamination()
    {
    	return $this->hasMany(OnlineExamination::class);
    }
}

resources/views/onlineexam/admin/course.blade.php
@extends('onlineexam.layouts.app')

@section('onlinecontent')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="navbar d-none d-md-block" 
                style="margin-bottom : -15px;">
                <ul class="navbar-nav d-flex flex-row gap-1 border-0">
                    <li class="nav-item">
                        <a href="{{ route('adminexam.index') }}" 
                            class="nav-link border border-bottom-0 text-light rounded py-3 px-5">
                            {{ __('Dashboard') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" 
                            class="nav-link border border-bottom-0 rounded py-3 bg-primary text-light px-5">
                            {{ __('Course') }}
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card border-top-0">
                <div class="card-header border border-primary bg-primary text-light py-4"></div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4 mb-3 mb-md-0">
                            <form method="POST" 
                                action="{{ route('courseexam.store') }}">
                                @csrf

                                <div class="row mb-3 justify-content-center">
                                    <div class="col">
                                        <div class="card border-warning">
                                            <div class="card-header border-bottom border-warning">
                                                {{ __('New Course') }}
                                            </div>
                                            <div class="card-body">
                                                <div class="form-group py-2">
                                                    <label for="course" 
                                                        class="mb-2">
                                                        {{ __('Course') }}
                                                    </label>
                                                    <input id="course" 
                                                        type="text" 
                                                        class="form-control @error('course') is-invalid @enderror" 
                                                        name="course" value="{{ old('course') }}" 
                                                        required 
                                                        autofocus>

                                                    @error('course')
                                                        <span class="invalid-feedback" 
                                                            role="alert">
                                                            <strong>
                                                                {{ $message }}
                                                            </strong>
                                                        </span>
                                                    @enderror
                                                </div>
                                                <div class="form-group d-flex justify-content-end">
                                                    <button type="submit" 
                                                        class="btn btn-outline-primary">
                                                        {{ __('Save') }}
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>        
                        <div class="col-md-8">
                            
                            <x-datatable 
                                :data="$courseList" 
                                title="Course List" 
                                :header="['Course']" 
                                :tData="['course']"
                                :hasEditButton="true"
                                editLink="courseexam.edit"
                            ></x-datatable>

                        </div>
                    </div>
                </div>
                <div class="card-footer bg-primary">
                    <div class="container">
                        <x-footerexam color="text-light"></x-footerexam>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/onlineexam/admin/index.blade.php
@extends('onlineexam.layouts.app')

@section('onlinecontent')
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <div class="navbar d-none d-md-block" 
                style="margin-bottom : -15px;">
                <ul class="navbar-nav d-flex flex-row gap-1 border-0">
                    <li class="nav-item">
                        <a href="#" 
                            class="nav-link border border-bottom-0 rounded py-3 bg-primary text-light px-5">
                            {{ __('Dashboard') }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('courseexam.index') }}" 
                            class="nav-link border border-bottom-0 text-light rounded py-3 px-5">
                            {{ __('Course') }}
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card border-top-0">
                <div class="card-header border border-primary bg-primary py-4"></div>
                <div class="card-body d-grid gap-3">
                    @php
                        $newTableData = [];

                        if(isset($users)) {
                            foreach($users as $user) {
                                $newRow = array(
                                    'id' => $user->id,
                                    'name' => $user->full_name,
                                    'gender' => $user->gender->gender,
                                    'course' => $user->onlinecourse->course,
                                    'userType' => 'For standalone system only',
                                    'changeStatus' => $user->trashed()
                                );
                            
                                array_push($newTableData, $newRow);
                            }
                        }
                    @endphp

                    <x-datatable 
                        :data="$users" 
                        :newTableData="$newTableData"
                        title="User List" 
                        :header="['Name', 'Gender', 'Course', 'User Type']" 
                        :tData="['name', 'gender', 'course', 'userType']"
                        :hasDeleteButton="true"
                        deleteLink="adminexam.destroy"
                    ></x-datatable>

                    @php
                        $newTableData2 = [];

                        if(isset($subjects)) {
                            foreach($subjects as $subject) {
                                $newRow2 = array(
                                    'id' => $subject->id,
                                    'subject' => $subject->subject,
                                    'createdby' => $subject->user->full_name
                                );
                            
                                array_push($newTableData2, $newRow2);
                            }
                        }
                    @endphp

                    <x-datatable 
                        :data="$subjects" 
                        :newTableData="$newTableData2"
                        title="Subject List" 
                        :header="['Subject', 'Created By']" 
                        :tData="['subject', 'createdby']"
                        :hasEditButton="true"
                        editLink="adminexam.edit"
                    ></x-datatable>

                </div>
                <div class="card-footer bg-primary">
                    <div class="container">
                        <x-footerexam color="text-light"></x-footerexam>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
@endsection