routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersPermissionController;
use App\Http\Controllers\UsersRoleController;
use App\Http\Controllers\InventoryController\web\DashboardController;
use App\Http\Controllers\InventoryController\web\ProductController;
use App\Http\Controllers\InventoryController\web\EmployeeController;
use App\Http\Controllers\InventoryController\web\EmployeeLogsController;
use App\Http\Controllers\InventoryController\web\ItemBrandController;
use App\Http\Controllers\InventoryController\web\ItemCategoryController;
use App\Http\Controllers\InventoryController\web\ItemColorController;
use App\Http\Controllers\InventoryController\web\ItemSizeController;
use App\Http\Controllers\InventoryController\web\ItemTypeController;
use App\Http\Controllers\InventoryController\web\OutOfStockItemController;
use App\Http\Controllers\InventoryController\web\MostOrderedItemController;
use App\Http\Controllers\InventoryController\web\NewProductListController;

use App\Http\Controllers\OnlineExamController\web\ProfileController;
use App\Http\Controllers\OnlineExamController\web\admin\AdminExamController;
use App\Http\Controllers\OnlineExamController\web\admin\AdminExamCourseController;
use App\Http\Controllers\OnlineExamController\web\faculty\FacultyExamDashboardController;
use App\Http\Controllers\OnlineExamController\web\faculty\ExamController;
use App\Http\Controllers\OnlineExamController\web\faculty\SubjectController;
use App\Http\Controllers\OnlineExamController\web\faculty\ExamQuestionController;
use App\Http\Controllers\OnlineExamController\web\student\StudentExamController;

use App\Http\Controllers\OnlineMenuController\web\AdminDashboardController;
use App\Http\Controllers\OnlineMenuController\web\CustomerDashboardController;

use App\Http\Controllers\PayrollController\web\admin\AdminPayrollDashboardController;
use App\Http\Controllers\PayrollController\web\admin\ScheduleController;
use App\Http\Controllers\PayrollController\web\admin\CutOffController;
use App\Http\Controllers\PayrollController\web\admin\AttendanceCorrectionController;
use App\Http\Controllers\PayrollController\web\admin\HolidayController;
use App\Http\Controllers\PayrollController\web\admin\SalaryAdditionController;
use App\Http\Controllers\PayrollController\web\admin\SalaryDeductionController;
use App\Http\Controllers\PayrollController\web\admin\SalaryGradeController;
use App\Http\Controllers\PayrollController\web\admin\UserRegistrationController;

use App\Http\Controllers\PayrollController\web\employee\EmployeePayrollDashboardController;

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::middleware(['auth', 'auth:sanctum'])->group(function () {
	Route::view('/', 'home')->name('index');

	/* User's Role and Permission route */
	Route::middleware('role:Super Admin')->group(function () {
		Route::resource('userspermission', UsersPermissionController::class);
		Route::resource('usersrole', UsersRoleController::class);
	});
	/* End */
	dd(Permission::with('users')->get());
	$permissionArr = array('inventory add stock', 'inventory get stock','inventory view user', 'inventory edit user', 'inventory add new item');
	$permissionStr = implode('|', $permissionArr);
	/* Inventory Route */
	// 'permission:inventory add stock|inventory get stock|inventory view user|inventory edit user|inventory add new item'
	Route::middleware('permission:'.$permissionStr)->prefix('inventory')->group(function() {
		Route::get('/', [DashboardController::class, 'index'])->name('inventorydashboard.index');

		Route::prefix('employee')->group(function() {
			Route::middleware('permission:inventory view user|inventory edit user')->group(function () {
				Route::get('/employeelogs', [EmployeeLogsController::class, 'index'])->name('employeelogs.index');
				Route::resource('employee', EmployeeController::class);
			});
		});

		Route::prefix('product')->group(function () {
			Route::resource('size', ItemSizeController::class);
			Route::resource('color', ItemColorController::class);
			Route::resource('brand', ItemBrandController::class);
			Route::resource('type', ItemTypeController::class);
			Route::resource('category', ItemCategoryController::class);
			Route::resource('outofstock', OutOfStockItemController::class);
			Route::resource('mostordered', MostOrderedItemController::class);
			Route::resource('newproduct', NewProductListController::class);

			Route::view('/deliver', 'inventory.product.receive')->name('deliver.index');
			Route::view('/order', 'inventory.product.order')->name('order.index');
			Route::view('/ordersummary', 'inventory.product.orderSummary')->name('ordersummary.index');
		});	
		
		Route::resource('product', ProductController::class);
	});
	/* END */

	/* Online Exam route */
	Route::prefix('online-exam')->group(function() {
		Route::middleware('permission:exam admin access')->group(function () {
			Route::resource('adminexam', AdminExamController::class);
			Route::resource('courseexam', AdminExamCourseController::class);
		});

		Route::middleware('permission:exam faculty access')->group(function () {
			Route::resource('facultyexam', FacultyExamDashboardController::class);
			Route::resource('exam', ExamController::class);
			Route::resource('subjectexam', SubjectController::class);
			Route::resource('examquestion', ExamQuestionController::class);
		});

		Route::middleware('permission:exam student access')->group(function () {
			Route::resource('studentexam', StudentExamController::class);
			Route::view('/examination', 'onlineexam.student.examination');
		});

		Route::resource('profile.user', ProfileController::class);
	});
	/* END */

	/* Online Menu route */
	Route::prefix('menu-ordering')->group(function() {
		/* Customer route */
		Route::middleware('permission:menu create orders|menu view order history|menu view coupon list')->group(function () {
			Route::get('/customer', [CustomerDashboardController::class, 'index'])->name('customer.index');
		});
		/* Admin Maintenance route */
		Route::middleware('permission:menu view order list|menu view user list')->group(function(){
			Route::get('/admin', [AdminDashboardController::class, 'index'])->name('admin.index');
		});
	});
	/* END */

	/* Payroll route */
	Route::prefix('payroll')->group(function() {
		Route::view('/notregister', 'payroll.notregister')->name('notregister.index');

		/* Admin */
		Route::middleware('permission:payroll admin access')->group(function() {
			Route::resource('payrolladmin', AdminPayrollDashboardController::class);
			Route::resource('payrollschedule', ScheduleController::class);
			Route::resource('cutoff', CutOffController::class);
			Route::resource('attendancecorrection', AttendanceCorrectionController::class);
			Route::resource('holiday', HolidayController::class);
			Route::resource('salaryaddition', SalaryAdditionController::class);
			Route::resource('salarydeduction', SalaryDeductionController::class);
			Route::resource('salarygrade', SalaryGradeController::class);
			Route::resource('register', UserRegistrationController::class);
		});

		/* Employee */
		Route::middleware('permission:payroll employee access')->group(function () {
			/* Check if user is registered in payroll system */
			Route::middleware('validatepayrolluser')->group(function () {
				Route::resource('payrollemployee', EmployeePayrollDashboardController::class);
			});
		});
		Route::resource('changepassword', PayrollChangePasswordController::class);
	});
});
/* END */

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles, SoftDeletes; 

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'password',
        'firstname', 
        'middlename', 
        'lastname', 
        'email', 
        'gender_id', 
        'online_course_id', 
        'DOB'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'remember_token',
        'password',
    ];
    
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'DOB' => 'date',
        'gender_id' => 'integer',
    ];

    protected $attributes = [
        'middlename' => null,
        'online_course_id' => 1,
    ];

    /* accessor */
    protected function getFullNameAttribute()
    {
        return "{$this->lastname}, {$this->firstname} {$this->middlename}";
    }

    /* Laravel 8 mutators */
    protected function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /* Local Scope */
    public function scopeNotadmin($query)
    {   
        return $query->where('id', '>', 1);
    }

    public function scopeNotself($query, $id)
    {
        return $query->where('id', '!=', $id);
    }

    public function onlinecourse()
    {
        return $this->belongsTo(OnlineCourse::class, 'online_course_id');
    }

    public function gender()
    {
        return $this->belongsTo(Gender::class);
    }

    public function onlinesubject()
    {
        return $this->hasMany(OnlineSubject::class);
    }

    public function onlineexam()
    {
        return $this->hasMany(OnlineExam::class);
    }

    public function onlineexamination()
    {
        return $this->hasMany(OnlineExamination::class);
    }

    public function inventoryreceive()
    {
        return $this->hasMany(InventoryItemReceive::class);
    }

    public function inventoryorder()
    {
        return $this->hasMany(InventoryItemOrder::class);
    }

    public function employeelog()
    {
        return $this->hasMany(InventoryEmployeeLog::class);
    }

    public function payrollcutoff()
    {
        return $this->hasMany(PayrollCutOff::class);
    }

    public function payrollemployee()
    {
        return $this->hasOne(PayrollEmployee::class);
    }

    public function approverattendancerequest()
    {
        return $this->hasMany(PayrollAttendanceRequest::class, 'approver_id');
    }

    public function requestorattendancerequest()
    {
        return $this->hasMany(PayrollAttendanceRequest::class, 'employee_id');
    }
}

resources/views/payroll/admin/addition.blade.php
@extends('payroll.layouts.app')

@section('payrollcontent')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<div class="card shadow">
					<div class="card-header">
						{{ __('Salary Addition') }}
					</div>
					<div class="card-body">
						<form method="POST" 
							action="{{ route('salaryaddition.store') }}" 
							class="px-5">

							@csrf

							@php
								$name = null; 
								$rate = 0;
								$amount = 0;
								$addid = 0;

								if(isset($addition)) {
									$name = $addition->name;
									$rate = $addition->rate;
									$amount = $addition->amount;
									$addid = $addition->id;
								}
							@endphp

							<div class="form-group pb-2">
								<label for="name">
									{{ __('Name') }}
								</label>
								<input type="text" 
									name="name" 
									class="form-control @error('name') is-invalid @enderror" 
									id="name" 
									value="{{ $name ?? old('name') }}" 
									{{ $name ? 'readonly' : '' }}>

								@error('name')
                	<span class="invalid-feedback" 
                		role="alert">

                    <strong>
                    	{{ $message }}
                    </strong>
                  </span>
                @enderror
							</div>

							<div class="form-group pb-4">
								<label for="amount">
									{{ __('Amount per minute') }}
								</label>
								<input type="number" 
									name="amount" 
									id="amount" 
									class="form-control @error('amount') is-invalid @enderror"
									value="{{ $amount ?? old('amount') }}">

								@error('amount')
                  <span class="invalid-feedback" 
                  	role="alert">

                		<strong>
                			{{ $message }}
                		</strong>
                  </span>
                @enderror
							</div>

							<div class="form-group pb-4">
								<label for="rate">
									{{ __('Rate in (%)') }}
								</label>
								<input type="number" 
									name="rate" 
									id="rate" 
									class="form-control @error('rate') is-invalid @enderror"
									value="{{ $rate * 100 ?? old('rate') }}">

								@error('rate')
	                <span class="invalid-feedback" 
	                	role="alert">

	                	<strong>
	                		{{ $message }}
	                	</strong>
	                </span>
                @enderror
							</div>

							@if(\Session::has('message'))
								<div class="fw-bold">
									{{ \Session::get('message') }}
								</div>
							@endif

							<input type="hidden" 
								name="id" 
								value="{{ $addid }}">

							<div class="form-group d-flex justify-content-between py-3">
								<a href="{{ route('payrolladmin.index') }}" 
									class="btn btn-outline-success">
									{{ __('Back') }}
								</a>
								<input type="submit" 
									value="Save" 
									class="btn btn-outline-primary">
									
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<x-footerexam :color="'text-dark'"/>
	</div>
@endsection

resources/views/payroll/admin/attendancerequest.blade.php
@extends('payroll.layouts.app')

@section('payrollcontent')
	<div class="container">
		<div class="row justify-content-center pb-3">
			<div class="col">
				<div class="card shadow">
					<div class="card-header">
						{{ __('Attendance Change Request') }}
					</div>
					<div class="card-body">
						<div class="table-responsive">
							<table class="table table-bordered table-striped">
								<thead>
									<th>
										{{ __('Employee Name') }}
									</th>
									<th>
										{{ __('Date Requested') }}
									</th>
									<th>
										<span class="d-flex flex-column">
											<span class="text-center">
												{{ __('Actual Attendance') }}
											</span>
											<span class="d-flex justify-content-around">
												<span class="small">
													{{ __('In') }}
												</span>
												<span class="small">
													{{ __('Out') }}
												</span>
												<span class="small">
													{{ __('In') }}
												</span>
												<span class="small">
													{{ __('Out') }}
												</span>
											</span>
										</span>
									</th>
									<th>
										<span class="d-flex flex-column">
											<span class="text-center">
												{{ __('For Approval') }}
											</span>
											<span class="d-flex justify-content-around">
												<span class="small">
													{{ __('In') }}
												</span>
												<span class="small">
													{{ __('Out') }}
												</span>
												<span class="small">
													{{ __('In') }}
												</span>
												<span class="small">
													{{ __('Out') }}
												</span>
											</span>
										</span>
									</th>
									<th>
										{{ __('Remarks') }}
									</th>
									<th>
										{{ __('Action') }}
									</th>
								</thead>
								<tbody>
									@forelse($attendances as $attendance)
										<tr class="small fw-bold">
											<td>
												{{ $attendance->employee->full_name }}
											</td>
											<td>
												{{ date('Y-m-d', strtotime($attendance->created_at)) }}
											</td>
											<td>
												<table class="w-100">
													<tr class="small">
														<td>
															{{ date('h:i a', strtotime($attendance->attendance->time_in)) }}
														</td>
														<td>
															{{ date('h:i a', strtotime($attendance->attendance->time_out_break)) }}
														</td>
														<td>
															{{ date('h:i a', strtotime($attendance->attendance->time_in_break)) }}
														</td>
														<td>
															{{ date('h:i a', strtotime($attendance->attendance->time_out)) }}
														</td>
													</tr>
												</table>
											</td>
											<td>
												<table class="w-100">
													<tr class="small">
														<td>
															{{ date('h:i a', strtotime($attendance->time_in)) }}
														</td>
														<td>
															{{ date('h:i a', strtotime($attendance->time_out_break)) }}
														</td>
														<td>
															{{ date('h:i a', strtotime($attendance->time_in_break)) }}
														</td>
														<td>
															{{ date('h:i a', strtotime($attendance->time_out)) }}
														</td>
													</tr>
												</table>
											</td>
											<td>
												{{ $attendance->remarks }}
											</td>
											<td>
												<table class="w-100">
													<tr>
														<td>
															<form method="POST" 
																action="{{ route('attendancecorrection.update', $attendance->id) }}">

																@csrf
																@method('PATCH')

																<div class="form-group">
																	<input type="hidden" 
																		name="status" 
																		value="1">

																	<input type="submit" 
																		value="Approve" 
																		class="btn btn-sm btn-outline-success">

																</div>
															</form>
														</td>
														<td>
															<form method="POST" 
																action="{{ route('attendancecorrection.update', $attendance->id) }}">

																@csrf
																@method('PATCH')

																<div class="form-group">
																	<input type="hidden" 
																		name="status" 
																		value="2">

																	<input type="submit" 
																		value="Reject" 
																		class="btn btn-sm btn-outline-danger">
																		
																</div>
															</form>
														</td>
													</tr>
												</table>
											</td>
										</tr>
									@empty
									@endforelse
								</tbody>
							</table>
							<div class="d-flex justify-content-end">
								@isset($attendance)
									{{ $attendance->links() }}
								@endisset
							</div>
						</div>
					</div>
				</div>
			</div>	
		</div>
	</div>
	<div class="container">
		<x-footerexam :color="'text-dark'"/>
	</div>
@endsection

resources/views/payroll/admin/holiday.blade.php
@extends('payroll.layouts.app')

@section('payrollcontent')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<div class="card shadow">
					<div class="card-header">
						{{ __('Holiday') }}
					</div>
					<div class="card-body">
						@php
							$name = null;
							$legal = 0;
							$local = 0;
							$day = '0';
							$month = '0';
							$rate = 0;
							$holid = 0;

							if(isset($holiday))
							{
								$arr = explode('-', $holiday->date);
								$name = $holiday->name;
								$day = $arr[1];
								$month = $arr[0];
								$legal = $holiday->is_legal;
								$local = $holiday->is_local;
								$rate = $holiday->rate;
								$holid = $holiday->id;
							}
						@endphp
						<form method="POST" 
							action="@if ($holid) {{ route('holiday.update', $holiday->id) }} @else {{ route('holiday.store') }} @endif" 
							class="px-5">

							@csrf

							@isset($holiday)
								@method('PATCH')
							@endisset

							<div class="form-group pb-2">
								<label for="name">
									{{ __('Name') }}
								</label>
								<input type="text" 
									name="name" 
									class="form-control @error('name') is-invalid @enderror" 
									id="name" 
									value="{{ $name ?? old('name') }}" 
									{{ $name ? 'readonly' : '' }}>

								@error('name')
	                <span class="invalid-feedback" 
	                	role="alert">

	                	<strong>
	                		{{ $message }}
	                	</strong>
	                </span>
                @enderror
							</div>

							<div class="form-group pb-2">
								<label for="month">
									{{ __('Date') }}
								</label>
								<div class="d-flex gap-2">
									<select class="form-select" 
										name="month" 
										id="month">

										<option value="1" 
											{{ $month == '1' ? 'selected' : 'selected' }}>
											{{ __('January') }}
										</option>
										<option value="2" 
											{{ $month == '2' ? 'selected' : '' }}>
											{{ __('February') }}
										</option>
										<option value="3" 
											{{ $month == '3' ? 'selected' : '' }}>
											{{ __('March') }}
										</option>
										<option value="4" 
											{{ $month == '4' ? 'selected' : '' }}>
											{{ __('April') }}
										</option>
										<option value="5" 
											{{ $month == '5' ? 'selected' : '' }}>
											{{ __('May') }}
										</option>
										<option value="6" 
											{{ $month == '6' ? 'selected' : '' }}>
											{{ __('June') }}
										</option>
										<option value="7" 
											{{ $month == '7' ? 'selected' : '' }}>
											{{ __('July') }}
										</option>
										<option value="8" 
											{{ $month == '8' ? 'selected' : '' }}>
											{{ __('August') }}
										</option>
										<option value="9" 
											{{ $month == '9' ? 'selected' : '' }}>
											{{ __('September') }}
										</option>
										<option value="10" 
											{{ $month == '10' ? 'selected' : '' }}>
											{{ __('October') }}
										</option>
										<option value="11" 
											{{ $month == '11' ? 'selected' : '' }}>
											{{ __('November') }}
										</option>
										<option value="12" 
											{{ $month == '12' ? 'selected' : '' }}>
											{{ __('December') }}
										</option>
									</select>
									<select class="form-select w-50" 
										name="day" 
										id="day">

										@isset($holiday)
											<option value="{{ $day }}" 
												selected>
												{{ $day }}
											</option>
										@endisset
									</select>
								</div>
							</div>
							
							<div class="form-group pb-3">
								<input type="checkbox" 
									name="islegal" 
									id="islegal" 
									value="1" 
									class="form-check-input"
									{{ $legal == 1 ? 'checked' : '' }}>

								<label class="form-check-label" 
									for="islegal">
									{{ __('Legal Holiday') }}
								</label>
							</div>

							<div class="form-group pb-3">
								<input type="checkbox" 
									name="islocal" 
									id="islocal" 
									value="1" 
									class="form-check-input"
									{{ $local == 1 ? 'checked' : '' }}>

								<label class="form-check-label" 
									for="islocal">
									{{ __('Local Holiday') }}
								</label>
							</div>

							<div class="form-group pb-4">
								<label for="rate">
									{{ __('Rate in (%)') }}
								</label>
								<input type="number" 
									name="rate" 
									id="rate" 
									class="form-control @error('rate') is-invalid @enderror"
									value="{{ $rate * 100 ?? old('rate') }}">

								@error('rate')
	                <span class="invalid-feedback" 
	                	role="alert">

	                	<strong>
	                		{{ $message }}
	                	</strong>
	                </span>
	              @enderror
							</div>

							@if(\Session::has('message'))
								<div class="fw-bold">
									{{ \Session::get('message') }}
								</div>
							@endif
							<input type="hidden" 
								name="id" 
								value="{{ $holid }}">

							<div class="form-group d-flex justify-content-between py-3">
								<a href="{{ route('payrolladmin.index') }}" 
									class="btn btn-outline-success">
									{{ __('Back') }}
								</a>
								<input type="submit" 
									value="Save" 
									class="btn btn-outline-primary">

							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<x-footerexam :color="'text-dark'"/>
	</div>

	<script type="text/javascript">
		$(document).ready(function(){
			const d = new Date();
			var year = d.getFullYear(),
				month = $('#month'),
				day = $('#day'),
				number_of_days = 0;

			number_of_days = daysInMonth(1, year);
			
			for (var i = 1; i <= number_of_days; i++) {
				$(day).append(`<option value="${i}">${i}</option>`);
			}
			
			$(month).on('change', function() {
				$(day).empty();
				number_of_days = daysInMonth(parseInt(this.value), year);
			  	for (var i = 1; i <= number_of_days; i++) {
					$(day).append(`<option value="${i}">${i}</option>`);
				}
			});

			/* get the number of days per month */
			function daysInMonth (month, year) {
			    return new Date(year, month, 0).getDate();
			}
			
		});
	</script>
@endsection

resources/views/payroll/admin/workschedule.blade.php
@extends('payroll.layouts.app')

@section('payrollcontent')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<div class="card shadow">
					<div class="card-header">
						{{ __('Work Schedule') }}
					</div>
					<div class="card-body">
						@php

							$name = null;
							$code = null;
							$startDT = null;
							$endDT = null;
							$sched_id = 0;

							if(isset($workschedule)) {
								$name = $workschedule->name;
								$code = $workschedule->code;
								$schedule = explode('-', $workschedule->schedule);
								$startDT = trim($schedule[0]);
								$endDT = trim($schedule[1]);
								$sched_id = $workschedule->id;
							}

						@endphp

						<form method="POST" 
							action="@if ($sched_id) 
												{{ route('payrollschedule.update', $workschedule->id) }} 
											@else
												{{ route('payrollschedule.store') }} 
											@endif" 
							class="px-5">
							@csrf

							@isset($workschedule)
								@method('PATCH')
							@endisset
							
							<div class="form-group pb-2">
								<label for="name">
									{{ __('Name') }}
								</label>
								<input type="text" 
									name="name" 
									class="form-control @error('name') is-invalid @enderror" 
									id="name" 
									value="{{ $name ?? old('name') }}" 
									{{ $name ? 'readonly' : '' }}>

								@error('name')
	                <span class="invalid-feedback" 
	                	role="alert">

	                	<strong>
	                		{{ $message }}
	                	</strong>
	                </span>
                @enderror
							</div>

							<div class="form-group pb-2">
								<label for="code">
									{{ __('Code') }}
								</label>
								<input type="text" 
									name="code" 
									class="form-control @error('code') is-invalid @enderror" 
									id="code" 
									value="{{ $code ?? old('code') }}" 
									{{ $code ? 'readonly' : '' }}>

								@error('code')
                  <span class="invalid-feedback" 
                  	role="alert">

                  	<strong>
                  		{{ $message }}
                  	</strong>
                  </span>
                @enderror
							</div>

							<div class="d-flex flex-column flex-md-row justify-content-md-between">
								<div class="form-group pb-2">
									<label for="startTme">
										{{ __('Time In') }}
									</label>
									<input type="time" 
										name="startTme" 
										class="form-control @error('startTme') is-invalid @enderror" 
										id="startTme" 
										value="{{ $startDT ?? old('startTme') ?? date('H:i') }}">

									@error('startTme')
	                  <span class="invalid-feedback" 
	                  	role="alert">

	                  	<strong>
	                  		{{ $message }}
	                  	</strong>
	                  </span>
                  @enderror
								</div>

								<div class="form-group pb-2">
									<label for="endTme">
										{{ __('Time Out') }}
									</label>

									<input type="time" 
										name="endTme" 
										class="form-control @error('endTme') is-invalid @enderror" 
										id="endTme" 
										value="{{ $endDT ?? old('endTme') ?? date('H:i') }}">

									@error('endTme')
	                  <span class="invalid-feedback" 
	                  	role="alert">

	                  	<strong>
	                  		{{ $message }}
	                  	</strong>
	                  </span>
                  @enderror
								</div>
							</div>

							@if(\Session::has('message'))
								<div class="fw-bold">
									{{ \Session::get('message') }}
								</div>
							@endif
							<input type="hidden" 
								name="id" 
								value="{{ $sched_id }}">

							<div class="form-group d-flex justify-content-between py-3">
								<a href="{{ route('payrolladmin.index') }}" 
									class="btn btn-outline-success">
									{{ __('Back') }}
								</a>
								<input type="submit" 
									value="Save" 
									class="btn btn-outline-primary">

							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="container">
		<x-footerexam :color="'text-dark'"/>
	</div>
@endsection